require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml
  - .rubocop/naming.yml
  - .rubocop/style.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.6
